name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or your desired Node.js version

    - name: Install dependencies
      run: |
        npm install  # Adjust this if you're using a different package manager

    - name: Build the project
      run: |
        npm run build  # Adjust this command according to your build script

    - name: Deploy to Azure Static Web Apps
      uses: "Azure/static-web-apps-deploy@v1"
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GRASS_0B10EBD10 }}
        action: "upload"
        app_location: "/"  # The path to your app (relative to repository root, modify if needed)
        output_location: "build"  # Adjust based on where your built files are outputted
